<?php 
$action	 	= $this->action;
$username 	= $this->username;
$errors 	= $this->errors;
echo $this->render('header.phtml'); ?>

<?php 
if ($action == 'confirm') { 
	if (count($errors) == 0) {	
?>
	<p>La tua nuova password è stata attivata.</p>
	<p><a href="/account/login">Accedi al tuo account</a></p>
	
<?php } else {  ?>
	<p>
		La tua nuova password non è stata confermata.
		Si prega di verificare il link a te inviato via email o di utilizzare nuovamente
		lo strumento di <a href="/account/recuperopassword">recupero password</a>
	</p>

<?php
	}	
} else if ($action == 'complete') {
?>
	<p>
		La tua nuova password ti è stata inviata all'indirizzo e-mail del tuo account.
		Devi cliccare il link in questa email per attivare la nuova password.
	</p>
<?php } else { ?>

<form method="post" action="/account/recupero-password">

	<fieldset>	
	
		<legend>Recupero password</legend>
		
		<div class="row" id="form_username_container">
			<label for="form_username">Username:</label>
			<input type="text" name="username" id="form_username" value="<?php echo $username; ?>" />
			<?php echo $this->partial('lib/error.phtml', array('error' => $errors, 'chiave' => 'username')); ?>			
		</div>
		
		<div class="submit">
			<input type="submit" value="Recupera password" />
		</div>
				
	</fieldset>	
</form>

<?php } ?>
<?php echo $this->render('footer.phtml'); ?>
