#nome#, Password del tuo account.
Caro #nome#,<br />
<br />
Hai recentemente richiesto il reset della password dimenticata.
La nuova password è riportata di seguito.
Per attivare quest password fai cli su questo link:
<br /><br />
Attiva password: 
http://phpweb20:8070/account/recupero-password?action=confirm&id=#idUtente#&key=#newPasswordKey#
<br />
Nome Utente : <strong>#username#</strong><br />
Nuova Password : <strong>#newPassword#</strong><br />

Se non hai richiesto il reset della password, ignora questo messaggio 
e la tua password non cambierà.
<br /><br />
Cordialmente,<br />
Amministratore sito web