<?php echo $this->render('header.phtml'); ?>

<?php 
if ($this->search['performed']) {
	if ($this->search['total'] == 0) {
		echo '<p>Nessun risultato trovato per questa ricerca.</p>'; 
	} else {
		echo '<p>Visualizzazione risultati ' . $this->search['start'] . '-' . $this->search['finish'] . '</p>';
		
		foreach ($this->search['results'] as $post){
			$id_utente = $post->id_utente;
			echo $this->partial('user/lib/blog-post-summary.phtml', array('post' => $post, 
																		  'user' => $this->users[$id_utente], 
																		  'linkToBlog' => true));
		}
			
		echo '<div class="pager">';
		for ($i = 0; $i < $this->search['pages']; $i++) {
			$p = $i + 1;
			if ($p == $this->search['page']) {
				echo '<strong>' . $p . '</strong>';
			} else {
				echo '<a href="' . $this->geturl(array('controller' => 'search')) . '?q=' . $this->q .'&amp;p=' . $p .'">';
				echo $p;
				echo '</a>';
			}
		}
		echo '</div>';		
	}
} else {
	echo '<p>Si prega di usare il form sulla sinistra per trovare i contenuti</p>';
}
?>
<?php echo $this->render('footer.phtml'); ?>