<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	  <title>Si è verificato un errore di sistema</title>
	</head>
	<body>
		<p>Si è verificato un errore al completamento della sua richiesta, la preghiamo di riprovare a breve. L'amministratore di sistema è stato avvisato del problema.</p>
	</body>
</html>
